name: Develop

on:
  push:
    branches:
      - develop
      
jobs:

  phpunit:
    name: Unit and Feature Tests
    runs-on: ubuntu-latest-m
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_pgsql, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, calendar, pcov-1.0.10, sodium
          coverage: pcov 
      # - name: Install Dependencies
            # run: 
              # composer install 

  phpmd-linter:
    name: PHPMD
    runs-on: ubuntu-latest-m
    steps:
      - name: Check out code into the workspace
        uses: actions/checkout@v3
      - name: Run php check code with reviewdog
        uses: GeneaLabs/action-reviewdog-phpmd@1.0.4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: 'warning'
          reporter: github-check
          standard: 'phpmd.xml'
          target_directory: '.'
            
  phpcs-linter:
    name: PHPCS
    runs-on: ubuntu-latest-m
    steps:
      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_pgsql, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, calendar
      - name: Check out code into the workspace
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          composer install --prefer-dist
      - name: PHPCS code anlaysis with ReviewDog
        uses: GeneaLabs/action-reviewdog-phpcs@1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: "warning"
          reporter: github-check
          standard: "./phpcs.xml"
          target_directory: './app'
          executable: './vendor/bin/phpcs'

  phpstan-linter:
    name: PHPStan
    runs-on: ubuntu-latest-m
    steps:
      - name: Check out code into the workspace
        uses: actions/checkout@v3
      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, calendar
      - name: Install Dependencies
        run: |
          composer install --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Run php check code with reviewdog
        uses: GeneaLabs/action-reviewdog-phpstan@1.1.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: 'error'
          reporter: github-check
          target_directory: 'src' 
