name: Develop

on:
  push:
    branches:
      - develop
      
jobs:

  phpunit:
    name: Unit and Feature Tests
    runs-on: ubuntu-latest-m
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_pgsql, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, calendar, pcov-1.0.10, sodium
          coverage: pcov 
