name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  phpmd-linter:
    name: PHPMD
    runs-on: ubuntu-latest-m
    steps:
      - name: Check out code into the workspace
        uses: actions/checkout@v3
      - name: Run php check code with reviewdog
        uses: GeneaLabs/action-reviewdog-phpmd@1.0.4
        with:
          level: 'warning'
          reporter: github-check
          standard: 'phpmd.xml'
          target_directory: '.'
